package com.tw.twshop.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table productimg
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Productimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.src
     *
     * @mbg.generated
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.id
     *
     * @return the value of productimg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.id
     *
     * @param id the value for productimg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.goods_id
     *
     * @return the value of productimg.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.goods_id
     *
     * @param goodsId the value for productimg.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.src
     *
     * @return the value of productimg.src
     *
     * @mbg.generated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.src
     *
     * @param src the value for productimg.src
     *
     * @mbg.generated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}