package com.tw.twshop.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Product {
    /**
     * Database Column Remarks:
     *   商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productname
     *
     * @mbg.generated
     */
    private String productname;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   商品类目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryid
     *
     * @mbg.generated
     */
    private Short categoryid;

    /**
     * Database Column Remarks:
     *   商品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.psn
     *
     * @mbg.generated
     */
    private String psn;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.displayorder
     *
     * @mbg.generated
     */
    private Short displayorder;

    /**
     * Database Column Remarks:
     *   默认状态为0，0：正常；1：已下架；2:已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stockcount
     *
     * @mbg.generated
     */
    private Integer stockcount;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.salecount
     *
     * @mbg.generated
     */
    private Integer salecount;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     *   成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.costprice
     *
     * @mbg.generated
     */
    private BigDecimal costprice;

    /**
     * Database Column Remarks:
     *   市场价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.marketprice
     *
     * @mbg.generated
     */
    private BigDecimal marketprice;

    /**
     * Database Column Remarks:
     *   评价数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.reviewcount
     *
     * @mbg.generated
     */
    private Integer reviewcount;

    /**
     * Database Column Remarks:
     *   访问数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.visitcount
     *
     * @mbg.generated
     */
    private Integer visitcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.showimg
     *
     * @mbg.generated
     */
    private String showimg;

    /**
     * Database Column Remarks:
     *   是否为精品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isbest
     *
     * @mbg.generated
     */
    private Byte isbest;

    /**
     * Database Column Remarks:
     *   是否为热销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ishot
     *
     * @mbg.generated
     */
    private Byte ishot;

    /**
     * Database Column Remarks:
     *   是否为新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isnew
     *
     * @mbg.generated
     */
    private Byte isnew;

    /**
     * Database Column Remarks:
     *   是否促销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ispromotion
     *
     * @mbg.generated
     */
    private Byte ispromotion;

    /**
     * Database Column Remarks:
     *   促销价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.promotionprice
     *
     * @mbg.generated
     */
    private BigDecimal promotionprice;

    /**
     * Database Column Remarks:
     *   是否显示价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isshowprice
     *
     * @mbg.generated
     */
    private Byte isshowprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productname
     *
     * @return the value of product.productname
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productname
     *
     * @param productname the value for product.productname
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryid
     *
     * @return the value of product.categoryid
     *
     * @mbg.generated
     */
    public Short getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryid
     *
     * @param categoryid the value for product.categoryid
     *
     * @mbg.generated
     */
    public void setCategoryid(Short categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.psn
     *
     * @return the value of product.psn
     *
     * @mbg.generated
     */
    public String getPsn() {
        return psn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.psn
     *
     * @param psn the value for product.psn
     *
     * @mbg.generated
     */
    public void setPsn(String psn) {
        this.psn = psn == null ? null : psn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.displayorder
     *
     * @return the value of product.displayorder
     *
     * @mbg.generated
     */
    public Short getDisplayorder() {
        return displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.displayorder
     *
     * @param displayorder the value for product.displayorder
     *
     * @mbg.generated
     */
    public void setDisplayorder(Short displayorder) {
        this.displayorder = displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.state
     *
     * @return the value of product.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.state
     *
     * @param state the value for product.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stockcount
     *
     * @return the value of product.stockcount
     *
     * @mbg.generated
     */
    public Integer getStockcount() {
        return stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stockcount
     *
     * @param stockcount the value for product.stockcount
     *
     * @mbg.generated
     */
    public void setStockcount(Integer stockcount) {
        this.stockcount = stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.salecount
     *
     * @return the value of product.salecount
     *
     * @mbg.generated
     */
    public Integer getSalecount() {
        return salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.salecount
     *
     * @param salecount the value for product.salecount
     *
     * @mbg.generated
     */
    public void setSalecount(Integer salecount) {
        this.salecount = salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.addtime
     *
     * @return the value of product.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.addtime
     *
     * @param addtime the value for product.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updatetime
     *
     * @return the value of product.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updatetime
     *
     * @param updatetime the value for product.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.costprice
     *
     * @return the value of product.costprice
     *
     * @mbg.generated
     */
    public BigDecimal getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.costprice
     *
     * @param costprice the value for product.costprice
     *
     * @mbg.generated
     */
    public void setCostprice(BigDecimal costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.marketprice
     *
     * @return the value of product.marketprice
     *
     * @mbg.generated
     */
    public BigDecimal getMarketprice() {
        return marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.marketprice
     *
     * @param marketprice the value for product.marketprice
     *
     * @mbg.generated
     */
    public void setMarketprice(BigDecimal marketprice) {
        this.marketprice = marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.reviewcount
     *
     * @return the value of product.reviewcount
     *
     * @mbg.generated
     */
    public Integer getReviewcount() {
        return reviewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.reviewcount
     *
     * @param reviewcount the value for product.reviewcount
     *
     * @mbg.generated
     */
    public void setReviewcount(Integer reviewcount) {
        this.reviewcount = reviewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.visitcount
     *
     * @return the value of product.visitcount
     *
     * @mbg.generated
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.visitcount
     *
     * @param visitcount the value for product.visitcount
     *
     * @mbg.generated
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.showimg
     *
     * @return the value of product.showimg
     *
     * @mbg.generated
     */
    public String getShowimg() {
        return showimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.showimg
     *
     * @param showimg the value for product.showimg
     *
     * @mbg.generated
     */
    public void setShowimg(String showimg) {
        this.showimg = showimg == null ? null : showimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isbest
     *
     * @return the value of product.isbest
     *
     * @mbg.generated
     */
    public Byte getIsbest() {
        return isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isbest
     *
     * @param isbest the value for product.isbest
     *
     * @mbg.generated
     */
    public void setIsbest(Byte isbest) {
        this.isbest = isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ishot
     *
     * @return the value of product.ishot
     *
     * @mbg.generated
     */
    public Byte getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ishot
     *
     * @param ishot the value for product.ishot
     *
     * @mbg.generated
     */
    public void setIshot(Byte ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isnew
     *
     * @return the value of product.isnew
     *
     * @mbg.generated
     */
    public Byte getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isnew
     *
     * @param isnew the value for product.isnew
     *
     * @mbg.generated
     */
    public void setIsnew(Byte isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ispromotion
     *
     * @return the value of product.ispromotion
     *
     * @mbg.generated
     */
    public Byte getIspromotion() {
        return ispromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ispromotion
     *
     * @param ispromotion the value for product.ispromotion
     *
     * @mbg.generated
     */
    public void setIspromotion(Byte ispromotion) {
        this.ispromotion = ispromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotionprice
     *
     * @return the value of product.promotionprice
     *
     * @mbg.generated
     */
    public BigDecimal getPromotionprice() {
        return promotionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotionprice
     *
     * @param promotionprice the value for product.promotionprice
     *
     * @mbg.generated
     */
    public void setPromotionprice(BigDecimal promotionprice) {
        this.promotionprice = promotionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isshowprice
     *
     * @return the value of product.isshowprice
     *
     * @mbg.generated
     */
    public Byte getIsshowprice() {
        return isshowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isshowprice
     *
     * @param isshowprice the value for product.isshowprice
     *
     * @mbg.generated
     */
    public void setIsshowprice(Byte isshowprice) {
        this.isshowprice = isshowprice;
    }
}