package com.tw.twshop.mapper;

import com.tw.twshop.entity.Productimg;
import java.util.List;

public interface ProductimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated
     */
    int insert(Productimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated
     */
    List<Productimg> selectAll();
}