package com.tw.mapper;

import com.tw.entity.BrowsingHistory;

import java.util.List;

public interface BrowsingHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated
     */
    int insert(BrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated
     */
    List<BrowsingHistory> selectAll();
}