package com.tw.mapper;

import com.tw.entity.SkuCollection;

import java.util.List;

public interface SkuCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_collection
     *
     * @mbg.generated
     */
    int insert(SkuCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_collection
     *
     * @mbg.generated
     */
    List<SkuCollection> selectAll();
}