package com.tw.mapper;

import com.tw.entity.SkuImage;
import java.util.List;

public interface SkuImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    int insert(SkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    List<SkuImage> selectAll();
}