package com.tw.twshop.mapper;

import com.tw.twshop.entity.UserLog;
import java.util.List;

public interface UserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated
     */
    List<UserLog> selectAll();
}