package com.tw.twshop.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table category
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Category {
    /**
     * Database Column Remarks:
     *   分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   父级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   价格范围，用“|”分隔开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.price_range
     *
     * @mbg.generated
     */
    private String priceRange;

    /**
     * Database Column Remarks:
     *   层级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.layer
     *
     * @mbg.generated
     */
    private Byte layer;

    /**
     * Database Column Remarks:
     *   是否有子级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.has_child
     *
     * @mbg.generated
     */
    private Boolean hasChild;

    /**
     * Database Column Remarks:
     *   店铺
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   状态:0 正常 ;1 禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parent_id
     *
     * @return the value of category.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parent_id
     *
     * @param parentId the value for category.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.path
     *
     * @return the value of category.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.path
     *
     * @param path the value for category.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.sequence
     *
     * @return the value of category.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.sequence
     *
     * @param sequence the value for category.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.price_range
     *
     * @return the value of category.price_range
     *
     * @mbg.generated
     */
    public String getPriceRange() {
        return priceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.price_range
     *
     * @param priceRange the value for category.price_range
     *
     * @mbg.generated
     */
    public void setPriceRange(String priceRange) {
        this.priceRange = priceRange == null ? null : priceRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.layer
     *
     * @return the value of category.layer
     *
     * @mbg.generated
     */
    public Byte getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.layer
     *
     * @param layer the value for category.layer
     *
     * @mbg.generated
     */
    public void setLayer(Byte layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.has_child
     *
     * @return the value of category.has_child
     *
     * @mbg.generated
     */
    public Boolean getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.has_child
     *
     * @param hasChild the value for category.has_child
     *
     * @mbg.generated
     */
    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.shop_id
     *
     * @return the value of category.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.shop_id
     *
     * @param shopId the value for category.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.state
     *
     * @return the value of category.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.state
     *
     * @param state the value for category.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}