package com.tw.twshop.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table supplier
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Supplier {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   logo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     * Database Column Remarks:
     *   keywords
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * Database Column Remarks:
     *   链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   默认状态为0，0：正常；1：禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * Database Column Remarks:
     *   店铺
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.logo
     *
     * @return the value of supplier.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.logo
     *
     * @param logo the value for supplier.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.keywords
     *
     * @return the value of supplier.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.keywords
     *
     * @param keywords the value for supplier.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.desc
     *
     * @return the value of supplier.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.desc
     *
     * @param desc the value for supplier.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.url
     *
     * @return the value of supplier.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.url
     *
     * @param url the value for supplier.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sequence
     *
     * @return the value of supplier.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sequence
     *
     * @param sequence the value for supplier.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.state
     *
     * @return the value of supplier.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.state
     *
     * @param state the value for supplier.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.shop_id
     *
     * @return the value of supplier.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.shop_id
     *
     * @param shopId the value for supplier.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}