package com.tw.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_sku
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductSku {
    /**
     * Database Column Remarks:
     *   skuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku1
     *
     * @mbg.generated
     */
    private String sku1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku2
     *
     * @mbg.generated
     */
    private String sku2;

    /**
     * Database Column Remarks:
     *   默认状态为0，0：正常；1：已下架；2:已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.stock_count
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     * Database Column Remarks:
     *   销售数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sale_count
     *
     * @mbg.generated
     */
    private Integer saleCount;

    /**
     * Database Column Remarks:
     *   成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     * Database Column Remarks:
     *   市场价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     * Database Column Remarks:
     *   评价数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.review_count
     *
     * @mbg.generated
     */
    private String reviewCount;

    /**
     * Database Column Remarks:
     *   访问数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.visit_count
     *
     * @mbg.generated
     */
    private Integer visitCount;

    /**
     * Database Column Remarks:
     *   显示图片主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.show_image
     *
     * @mbg.generated
     */
    private String showImage;

    /**
     * Database Column Remarks:
     *   促销价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.promotion_price
     *
     * @mbg.generated
     */
    private BigDecimal promotionPrice;

    /**
     * Database Column Remarks:
     *   是否显示价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.show_price
     *
     * @mbg.generated
     */
    private Byte showPrice;

    /**
     * Database Column Remarks:
     *   是否为精品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.is_best
     *
     * @mbg.generated
     */
    private Byte isBest;

    /**
     * Database Column Remarks:
     *   是否为热销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.is_hot
     *
     * @mbg.generated
     */
    private Byte isHot;

    /**
     * Database Column Remarks:
     *   是否为新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.is_new
     *
     * @mbg.generated
     */
    private Byte isNew;

    /**
     * Database Column Remarks:
     *   是否促销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.is_promotion
     *
     * @mbg.generated
     */
    private Byte isPromotion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     * Database Column Remarks:
     *   sku编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku_sn
     *
     * @mbg.generated
     */
    private String skuSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   店铺
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.id
     *
     * @return the value of product_sku.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.id
     *
     * @param id the value for product_sku.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku1
     *
     * @return the value of product_sku.sku1
     *
     * @mbg.generated
     */
    public String getSku1() {
        return sku1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku1
     *
     * @param sku1 the value for product_sku.sku1
     *
     * @mbg.generated
     */
    public void setSku1(String sku1) {
        this.sku1 = sku1 == null ? null : sku1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku2
     *
     * @return the value of product_sku.sku2
     *
     * @mbg.generated
     */
    public String getSku2() {
        return sku2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku2
     *
     * @param sku2 the value for product_sku.sku2
     *
     * @mbg.generated
     */
    public void setSku2(String sku2) {
        this.sku2 = sku2 == null ? null : sku2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.state
     *
     * @return the value of product_sku.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.state
     *
     * @param state the value for product_sku.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.stock_count
     *
     * @return the value of product_sku.stock_count
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.stock_count
     *
     * @param stockCount the value for product_sku.stock_count
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sale_count
     *
     * @return the value of product_sku.sale_count
     *
     * @mbg.generated
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sale_count
     *
     * @param saleCount the value for product_sku.sale_count
     *
     * @mbg.generated
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.cost_price
     *
     * @return the value of product_sku.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.cost_price
     *
     * @param costPrice the value for product_sku.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.market_price
     *
     * @return the value of product_sku.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.market_price
     *
     * @param marketPrice the value for product_sku.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.review_count
     *
     * @return the value of product_sku.review_count
     *
     * @mbg.generated
     */
    public String getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.review_count
     *
     * @param reviewCount the value for product_sku.review_count
     *
     * @mbg.generated
     */
    public void setReviewCount(String reviewCount) {
        this.reviewCount = reviewCount == null ? null : reviewCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.visit_count
     *
     * @return the value of product_sku.visit_count
     *
     * @mbg.generated
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.visit_count
     *
     * @param visitCount the value for product_sku.visit_count
     *
     * @mbg.generated
     */
    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.show_image
     *
     * @return the value of product_sku.show_image
     *
     * @mbg.generated
     */
    public String getShowImage() {
        return showImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.show_image
     *
     * @param showImage the value for product_sku.show_image
     *
     * @mbg.generated
     */
    public void setShowImage(String showImage) {
        this.showImage = showImage == null ? null : showImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.promotion_price
     *
     * @return the value of product_sku.promotion_price
     *
     * @mbg.generated
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.promotion_price
     *
     * @param promotionPrice the value for product_sku.promotion_price
     *
     * @mbg.generated
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.show_price
     *
     * @return the value of product_sku.show_price
     *
     * @mbg.generated
     */
    public Byte getShowPrice() {
        return showPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.show_price
     *
     * @param showPrice the value for product_sku.show_price
     *
     * @mbg.generated
     */
    public void setShowPrice(Byte showPrice) {
        this.showPrice = showPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.is_best
     *
     * @return the value of product_sku.is_best
     *
     * @mbg.generated
     */
    public Byte getIsBest() {
        return isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.is_best
     *
     * @param isBest the value for product_sku.is_best
     *
     * @mbg.generated
     */
    public void setIsBest(Byte isBest) {
        this.isBest = isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.is_hot
     *
     * @return the value of product_sku.is_hot
     *
     * @mbg.generated
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.is_hot
     *
     * @param isHot the value for product_sku.is_hot
     *
     * @mbg.generated
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.is_new
     *
     * @return the value of product_sku.is_new
     *
     * @mbg.generated
     */
    public Byte getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.is_new
     *
     * @param isNew the value for product_sku.is_new
     *
     * @mbg.generated
     */
    public void setIsNew(Byte isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.is_promotion
     *
     * @return the value of product_sku.is_promotion
     *
     * @mbg.generated
     */
    public Byte getIsPromotion() {
        return isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.is_promotion
     *
     * @param isPromotion the value for product_sku.is_promotion
     *
     * @mbg.generated
     */
    public void setIsPromotion(Byte isPromotion) {
        this.isPromotion = isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.add_time
     *
     * @return the value of product_sku.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.add_time
     *
     * @param addTime the value for product_sku.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.update_time
     *
     * @return the value of product_sku.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.update_time
     *
     * @param updateTime the value for product_sku.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sequence
     *
     * @return the value of product_sku.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sequence
     *
     * @param sequence the value for product_sku.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku_sn
     *
     * @return the value of product_sku.sku_sn
     *
     * @mbg.generated
     */
    public String getSkuSn() {
        return skuSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku_sn
     *
     * @param skuSn the value for product_sku.sku_sn
     *
     * @mbg.generated
     */
    public void setSkuSn(String skuSn) {
        this.skuSn = skuSn == null ? null : skuSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.product_id
     *
     * @return the value of product_sku.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.product_id
     *
     * @param productId the value for product_sku.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.shop_id
     *
     * @return the value of product_sku.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.shop_id
     *
     * @param shopId the value for product_sku.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}