package com.tw.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sku_image
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SkuImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.sku_id
     *
     * @mbg.generated
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.src
     *
     * @mbg.generated
     */
    private String src;

    /**
     * Database Column Remarks:
     *   product_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_image.id
     *
     * @return the value of sku_image.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_image.id
     *
     * @param id the value for sku_image.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_image.sku_id
     *
     * @return the value of sku_image.sku_id
     *
     * @mbg.generated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_image.sku_id
     *
     * @param skuId the value for sku_image.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_image.src
     *
     * @return the value of sku_image.src
     *
     * @mbg.generated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_image.src
     *
     * @param src the value for sku_image.src
     *
     * @mbg.generated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_image.product_id
     *
     * @return the value of sku_image.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_image.product_id
     *
     * @param productId the value for sku_image.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}